turnitin/moodle-mod_turnitintool

lib.php, view.php
Fix module warning debug message.
=> Fix module warning debug message.

comms.php
Fix course reset assignment dates.
=> Fix course reset assignment dates.

lib.php
Increase number of decimals used for rounding grades.
=> Increase number of decimals used for rounding grades.

ChangeLog.txt, README.txt, version.php
Moodle Direct V1 release 2015030305
=> Release 2015030305

backup/moodle2/restore_turnitintool_stepslib.php
Fix for when e-mail address has changed between a backup and restore.
=> Fix for when e-mail address has changed between a backup and restore.

ChangeLog.txt, README.txt, version.php
Release notes and version number for v2016101201.
=> v2016101201

ChangeLog.txt, README.txt, version.php
=> Release 2016102701

ChangeLog.txt, README.txt
=> Release notes.

backup/moodle2/restore_turnitintool_stepslib.php
=> Bug fix for restore.

backup/moodle2/restore_turnitintool_stepslib.php
=> Changing >= to >

backup/moodle2/restore_turnitintool_stepslib.php, db/upgrade.php, lib.php, version.php
Change fix to use a UUID instead.
=> Restorebackup fix

db/upgrade.php
Revert change to upgrade file.
=> Revert update to submission hash.

db/upgrade.php
Change to versioning as master is ahead of our dev branch.
=> Change to versioning as master is ahead of our dev branch.

CHANGELOG.md
=> Small fix to changelog.

lib.php, styles.css, view.php
This pull request removes the deprecated update module button and adds the edit cog.
=> Remove the deprecated update module button.

styles.css
Fixes the textarea for submission comments.
=> Fixes the textarea for submission comments.

lib.php
Fix hash error that results from a multiple submission.
=> Fix hash error that results from a multiple submission.

styles.css, version.php, view.php
Migration tool commence screen
=> Migration tool commence screen

view.php
Rework logic checks and implement automatic migration.
=> Rework logic checks and implement automatic migration.

view.php
=> Fix colorbox undefined.

styles.css, view.php
Add loading spinner modal screen.
=> Add loading spinner modal screen.

view.php
If the user is an instructor or an admin, allow migration.
=> If the user is an instructor or an admin, allow migration

styles.css, view.php
=> Modal design CSS changes.

styles.css
=> INT-9028: Add migration error css

CHANGELOG.md, db/upgrade.php, version.php
=> Migration tool release.

CHANGELOG.md, db/upgrade.php, version.php
=> Migration tool release

styles.css
=> Ensure table rows in submission table display as table-row.
